#!/bin/bash

set -e

. /usr/lib/iserv/cfg

# Memory limit for prod environment
FPM_MEMORY_LIMIT="64M"

# Allow for more memory in the dev environment as the re-compiling of the container crashes otherwise
if [ "$DevEnvironment" == "1" ]
then
  FPM_MEMORY_LIMIT="256M"
fi

# generates *a* dynamic config. To see potential results just try using the command it on a VM you trust.
# dynamic is probably good for most normal modules.
# ondemand can also make sense for example for modules with low and very easy to calculate load (e.g. no users, but timers)
# static with the calculated high numbers is most likely a mistake.
/usr/lib/iserv/server-php/generate-fpm-config dynamic

cat << EOF
; Prüfe mich - ist dynamisch richtig?
; should be generated by the above command.
;pm = static
;pm.max_children = 5 ;
;pm.max_requests = 200
;pm.status_path = /status

; Dev and Prod environment have different memory limits
; Ändere mich! - RAM für Prod anpassen
php_value[memory_limit] = ${FPM_MEMORY_LIMIT}
php_value[session.save_path] = "/var/lib/iserv/unificonnector/sessions"

env["APP_SECRET_FILE"] = "/var/lib/iserv/unificonnector/pwd/symfony.secret"
env["POSTGRES_VERSION"] = "$(psql iserv postgres -Atc "SHOW SERVER_VERSION;")"
EOF

